import { useEffect, useRef, useState } from "react";
import { jsPDF } from "jspdf";
import { api } from "../api";

/** AI-assist UI (ADR-038, reworked per owner direction 2026-08-05):
 *  - CaseReport: one click fetches the SIU report and downloads it as a
 *    typeset PDF (client-side jsPDF — no backend change, works offline
 *    because the fallback template report downloads just the same).
 *  - ChatBubble: floating bottom-right analyst chat inside a case —
 *    suggested-question chips, sender right / analyst left alignment,
 *    typing indicator. Same context-bound endpoint; no automatic calls
 *    (free-tier posture). */

const SOURCE_TAGS = {
  "gemini-live": { label: "live AI (Gemini)", cls: "border-heat-high/60 text-heat-high" },
  fallback: { label: "deterministic template", cls: "border-paper-dim/50 text-paper-mut" },
};

function SourceTag({ source }) {
  const tag = SOURCE_TAGS[source] ?? SOURCE_TAGS.fallback;
  return (
    <span
      className={`shrink-0 rounded-sm border px-1.5 py-0.5 font-mono text-[9px] uppercase tracking-[0.1em] ${tag.cls}`}
    >
      {tag.label}
    </span>
  );
}

/* ---------------- PDF report ---------------- */

const HEADING_RE = /^[A-Z][A-Z ()/&-]{3,}$/;

function buildReportPdf(alertId, detail, reportText, source) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const margin = 56;
  const width = 595.28 - margin * 2;
  const bottom = 841.89 - margin;
  let y = margin;

  const ensureRoom = (needed) => {
    if (y + needed > bottom) {
      doc.addPage();
      y = margin;
    }
  };

  // letterhead
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("MEDGRAPH SENTINEL", margin, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(110);
  doc.text("Special Investigation Unit — case-file report (synthetic data)", margin, y + 14);
  doc.setTextColor(0);
  y += 34;
  doc.setDrawColor(180);
  doc.line(margin, y, margin + width, y);
  y += 20;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(`Alert ${alertId}`, margin, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  const meta = detail
    ? `${detail.typology}  ·  score ${detail.score} (${detail.severity})  ·  status ${detail.status}`
    : "";
  doc.text(meta, margin, y + 13);
  y += 32;

  doc.setFontSize(10);
  for (const raw of reportText.split(/\r?\n/)) {
    const line = raw.trimEnd();
    if (!line.trim()) {
      y += 6;
      continue;
    }
    if (HEADING_RE.test(line.trim())) {
      ensureRoom(26);
      y += 8;
      doc.setFont("helvetica", "bold");
      doc.text(line.trim(), margin, y);
      y += 15;
      doc.setFont("times", "normal");
      continue;
    }
    doc.setFont("times", "normal");
    for (const wrapped of doc.splitTextToSize(line, width)) {
      ensureRoom(14);
      doc.text(wrapped, margin, y);
      y += 13;
    }
  }

  ensureRoom(30);
  y += 12;
  doc.setDrawColor(180);
  doc.line(margin, y, margin + width, y);
  doc.setFontSize(8);
  doc.setTextColor(110);
  doc.text(
    `Generated by MedGraph Sentinel (${source === "gemini-live" ? "live AI draft" : "deterministic template"}) — ` +
      "investigation lead on synthetic data, not a finding of fraud.",
    margin,
    y + 12,
  );
  doc.save(`${alertId}-siu-report.pdf`);
}

export function CaseReport({ alertId, detail }) {
  const [state, setState] = useState({ status: "idle" });

  useEffect(() => setState({ status: "idle" }), [alertId]);

  const download = () => {
    setState({ status: "loading" });
    api
      .report(alertId)
      .then((r) => {
        buildReportPdf(alertId, detail, r.report, r.source);
        setState({ status: "done", source: r.source });
      })
      .catch((e) => setState({ status: "error", error: e.message }));
  };

  return (
    <section className="border-t border-ink-700 px-5 py-4">
      <div className="flex items-baseline justify-between gap-3">
        <h3 className="font-mono text-[10px] uppercase tracking-[0.2em] text-paper-dim">
          Case-file report
        </h3>
        {state.status === "done" && <SourceTag source={state.source} />}
      </div>
      <button
        onClick={download}
        disabled={state.status === "loading"}
        className="mt-3 rounded-sm border border-tracer/50 px-3 py-1.5 font-mono text-xs text-tracer hover:bg-tracer/10 disabled:opacity-40"
      >
        {state.status === "loading" ? "drafting…" : "Download SIU report (PDF)"}
      </button>
      {state.status === "done" && (
        <p className="mt-2 font-mono text-[10px] text-paper-dim">
          saved as {alertId}-siu-report.pdf — check your downloads
        </p>
      )}
      {state.status === "error" && (
        <p className="mt-2 font-mono text-xs text-heat-high">
          report failed: {state.error}
        </p>
      )}
    </section>
  );
}

/* ---------------- floating case chat ---------------- */

const SUGGESTED_BY_TYPOLOGY = {
  template_cloning: "What makes these claims clones of each other?",
  circular_payment: "Walk me through the money loop step by step",
  ghost_clinic: "What footprint is this clinic missing?",
  kickback_ring: "How concentrated is the referral flow here?",
  credential_laundering: "Who is using this licence and where?",
  impossible_travel: "Which claim pairs are physically impossible?",
};

function suggestions(typology, severity) {
  return [
    `Why did this alert score ${severity ?? "this"} severity?`,
    SUGGESTED_BY_TYPOLOGY[typology] ?? "Summarize the key evidence",
    "Could this be a false positive?",
    "What should I verify first?",
  ];
}

function TypingDots() {
  return (
    <div className="flex items-center gap-1 px-3 py-2">
      {[0, 150, 300].map((delay) => (
        <span
          key={delay}
          className="h-1.5 w-1.5 animate-bounce rounded-full bg-paper-dim"
          style={{ animationDelay: `${delay}ms` }}
        />
      ))}
    </div>
  );
}

export function ChatBubble({ alertId, typology, severity }) {
  const [open, setOpen] = useState(false);
  const [messages, setMessages] = useState([]);
  const [input, setInput] = useState("");
  const [busy, setBusy] = useState(false);
  const endRef = useRef(null);
  const inputRef = useRef(null);

  useEffect(() => {
    setMessages([]);
    setInput("");
    setBusy(false);
    setOpen(false);
  }, [alertId]);

  useEffect(() => {
    endRef.current?.scrollIntoView({ block: "nearest", behavior: "smooth" });
  }, [messages, busy, open]);

  const send = (textArg) => {
    const text = (textArg ?? input).trim();
    if (!text || busy) return;
    const next = [...messages, { role: "user", text }];
    setMessages(next);
    setInput("");
    setBusy(true);
    api
      .chat(alertId, next.slice(-12).map(({ role, text: t }) => ({ role, text: t })))
      .then((r) =>
        setMessages((m) => [...m, { role: "assistant", text: r.reply, source: r.source }]),
      )
      .catch((e) =>
        setMessages((m) => [
          ...m,
          { role: "assistant", text: `Something went wrong: ${e.message}`, source: "fallback" },
        ]),
      )
      .finally(() => {
        setBusy(false);
        inputRef.current?.focus();
      });
  };

  return (
    <>
      {/* launcher */}
      {!open && (
        <button
          onClick={() => setOpen(true)}
          aria-label="Open case analyst chat"
          className="fixed bottom-5 right-5 z-40 flex h-14 w-14 items-center justify-center rounded-full border border-tracer/60 bg-ink-900 text-tracer shadow-xl shadow-black/40 transition-transform hover:scale-105 hover:bg-ink-800"
        >
          <svg viewBox="0 0 24 24" className="h-6 w-6" fill="none" stroke="currentColor" strokeWidth="1.7">
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M8 10h8m-8 4h5m-9 6V7a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H9l-5 4z"
            />
          </svg>
        </button>
      )}

      {/* window */}
      {open && (
        <div className="fixed bottom-5 right-5 z-40 flex h-[30rem] w-[22rem] max-w-[calc(100vw-2.5rem)] flex-col overflow-hidden rounded-lg border border-ink-700 bg-ink-950 shadow-2xl shadow-black/60">
          {/* header */}
          <div className="flex items-center justify-between border-b border-ink-700 bg-ink-900 px-4 py-3">
            <div className="min-w-0">
              <div className="font-mono text-[10px] uppercase tracking-[0.2em] text-paper-dim">
                Case analyst
              </div>
              <div className="truncate font-mono text-xs text-paper">{alertId}</div>
            </div>
            <div className="flex items-center gap-2">
              <span className="h-2 w-2 rounded-full bg-tracer" title="context-bound AI" />
              <button
                onClick={() => setOpen(false)}
                aria-label="Close chat"
                className="rounded p-1 text-paper-dim hover:bg-ink-800 hover:text-paper"
              >
                <svg viewBox="0 0 24 24" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="2">
                  <path strokeLinecap="round" d="M6 6l12 12M18 6L6 18" />
                </svg>
              </button>
            </div>
          </div>

          {/* messages */}
          <div className="flex-1 space-y-3 overflow-y-auto px-3 py-3">
            {messages.length === 0 && (
              <div className="space-y-2">
                <p className="px-1 text-xs leading-relaxed text-paper-dim">
                  I answer from this alert's evidence only — nothing is
                  invented. Try one of these:
                </p>
                {suggestions(typology, severity).map((q) => (
                  <button
                    key={q}
                    onClick={() => send(q)}
                    className="block w-full rounded-md border border-ink-700 bg-ink-900 px-3 py-2 text-left text-xs text-paper/90 transition-colors hover:border-tracer/50 hover:text-tracer"
                  >
                    {q}
                  </button>
                ))}
              </div>
            )}
            {messages.map((m, i) => (
              <div key={i} className={`flex ${m.role === "user" ? "justify-end" : "justify-start"}`}>
                <div
                  className={
                    m.role === "user"
                      ? "max-w-[80%] rounded-2xl rounded-br-sm bg-tracer/20 px-3 py-2 text-[13px] leading-relaxed text-paper"
                      : "max-w-[85%] rounded-2xl rounded-bl-sm border border-ink-700 bg-ink-900 px-3 py-2 text-[13px] leading-relaxed text-paper/90"
                  }
                >
                  {m.text}
                  {m.role === "assistant" && m.source === "fallback" && (
                    <div className="mt-1 font-mono text-[9px] uppercase tracking-[0.1em] text-paper-dim">
                      offline reply
                    </div>
                  )}
                </div>
              </div>
            ))}
            {busy && (
              <div className="flex justify-start">
                <div className="rounded-2xl rounded-bl-sm border border-ink-700 bg-ink-900">
                  <TypingDots />
                </div>
              </div>
            )}
            <div ref={endRef} />
          </div>

          {/* input */}
          <div className="flex items-center gap-2 border-t border-ink-700 bg-ink-900 px-3 py-2.5">
            <input
              ref={inputRef}
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && send()}
              placeholder="Ask about this alert…"
              className="min-w-0 flex-1 rounded-full border border-ink-700 bg-ink-950 px-3.5 py-2 text-xs text-paper placeholder:text-paper-dim/60 focus:border-tracer/60 focus:outline-none"
            />
            <button
              onClick={() => send()}
              disabled={busy || !input.trim()}
              aria-label="Send"
              className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-tracer/20 text-tracer transition-colors hover:bg-tracer/30 disabled:opacity-40"
            >
              <svg viewBox="0 0 24 24" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="2">
                <path strokeLinecap="round" strokeLinejoin="round" d="M5 12h13m0 0-5-5m5 5-5 5" />
              </svg>
            </button>
          </div>
        </div>
      )}
    </>
  );
}
